from pysb import *
from MODULES.Lemaire2004 import create_model_elements as create_Lemaire_ME
from MODULES.Harris2024 import create_model_elements as create_Harris_ME
from MODULES.perturbations import add_bisphosphonate_components

Model()

create_Lemaire_ME()  # TODO: consider passing in a scaling factor to adjust concentration units (e.g., pM to cells/mm)
create_Harris_ME(OB_OC_BONE_MODEL=1)
# add_bisphosphonate_components()

# modify a few parameter values
R_0.value = 0.0  # fM
B_0.value = 0.0  # fM
C_0.value = 0.0  # fM
kB.value = 0.013  # /day

if __name__ == '__main__':

    from param_calibration import *
    from SIM_PROTOCOLS.sim_protocols import tumor_injection

    custom_priors = {'N': ('uniform', 0.3)}
    no_sample = ['R_0', 'B_0', 'C_0', 'f0', 'IL', 'IO', 'IP_const', 'Bone_0', 'nB', 'nC', 'Tumor_0', 'CC_ON',
                 'ALLEE_ON', 'A', 'Bisphos_0', 'k_bisphos_AOC']

    # Simple example using the ParameterCalibration class to run PyDREAM for a data set with only one experiment

    exp_data_file = '../DATA/TIBD_PopD_Mouse_Data.csv'
    calibrator = ParameterCalibration(model,
                                      exp_data_file,
                                      tumor_injection,
                                      priors=custom_priors,
                                      no_sample=no_sample)
    calibrator.run(niterations=50000, nchains=5, plot_results=True)

    # To run a more complex example involving a data set with two experiments where some parameter values can vary
    # between experiments, uncomment the code below
    '''
    exp_data_file = '../DATA/TIBD_PopD_Mouse_Data_2expts.csv'

    # If parameter values can vary between experiments, define groups of experiments where they are the same.
    # If a parameter value is unique to an experiment, the group will be length 1. The default is for parameter values
    # to be common across all experiments, in which case there will be one group containing indices for all experiments.
    # This is handled internally, so only need to define cases where param values are NOT common across all expts.
    param_expts_map = {'Cs': [['A', 'B']],  # this is just here to show what the default is
                       'k_tumor_div_basal': [['A'], ['B']],  # this and the following params can vary btwn the 2 expts
                       'k_tumor_dth': [['A'], ['B']],
                       'k_tumor_div_TGFb': [['A'], ['B']],
                       'k_tumor_PTHrP': [['A'], ['B']],
                       'k_tumor_OB': [['A'], ['B']],
                       'k_tumor_OC': [['A'], ['B']]}

    calibrator = ParameterCalibration(model,
                                      exp_data_file,
                                      [tumor_injection] * 2,
                                      priors=custom_priors,
                                      no_sample=no_sample,
                                      param_expts_map=param_expts_map)
    calibrator.run(niterations=50000, nchains=5, plot_results=True, plot_tc_args={'separate_plots': False})
    '''

    # To create plots using output files already generated by PyDREAM, comment out the calibrate.run() line above and
    # uncomment the code below
    '''
    import glob
    logps_files = glob.glob('dreamzs*logps*')
    samples_files = glob.glob('dreamzs*params*')
    calibrator.create_figures(logps_files, samples_files, show_plots=True, plot_tc_args={'separate_plots': False})
    '''
